export const formatIDR = (num) =>
  new Intl.NumberFormat('id-ID', { style: 'currency', currency: 'IDR', minimumFractionDigits: 0 }).format(num)

export const CATEGORIES = [
  'umroh', 'umroh-mandiri', 'muslim-tour', 'fit-products', 'wisata-populer', 'tour-reguler',
]

export const CATEGORY_LABELS = {
  'umroh':          'Umroh',
  'umroh-mandiri':  'Umroh Mandiri',
  'muslim-tour':    'Muslim Tour',
  'fit-products':   'FIT Products',
  'wisata-populer': 'Wisata Populer',
  'tour-reguler':   'Tour Reguler',
}

export const INITIAL_PRODUCTS = [
  {
    product_sku: 'UMR-REG-PLUS-12D-SEP26',
    category: 'umroh',
    badge_label: 'Terpopuler',
    title: '12D Umroh Reguler Plus',
    subtitle: 'Hotel Pelataran & Kereta Cepat',
    departure_date: '2026-09-10',
    airline: 'Qatar Airways',
    hotel_makkah: 'Al Sofwah Tower 1',
    hotel_madinah: 'Ruve Al Madinah',
    duration_days: 12,
    feature_tags: 'Free Fast Train, Hotel Pelataran',
    normal_price: 49700000,
    publish_price: 46700000,
    price_label: 'Jt/pax',
    cta_text: 'Detail Paket',
    is_active: true,
  },
  {
    product_sku: 'UMR-PREM-HEMAT-9D-OKT26',
    category: 'umroh',
    badge_label: 'Best Deal',
    title: '9D Umroh Premium Hemat',
    subtitle: 'Direct Landing Jeddah',
    departure_date: '2026-10-12',
    airline: 'Saudia Airlines',
    hotel_makkah: 'Grand Al Masa',
    hotel_madinah: 'Kayan International',
    duration_days: 9,
    feature_tags: 'Direct Landing, Premium Hemat',
    normal_price: 35600000,
    publish_price: 31680000,
    price_label: 'Jt/pax',
    cta_text: 'Detail Paket',
    is_active: true,
  },
  {
    product_sku: 'TOUR-TURKIYE-10D-OKT26',
    category: 'muslim-tour',
    badge_label: 'Favorit',
    title: '10D Jelajah Turkiye Halal Tour',
    subtitle: 'Istanbul, Cappadocia & Pamukkale',
    departure_date: '2026-10-15',
    airline: 'Turkish Airlines',
    hotel_makkah: '',
    hotel_madinah: '',
    duration_days: 10,
    feature_tags: 'Bintang 4/5, Cappadocia Cave Hotel',
    normal_price: 26500000,
    publish_price: 24800000,
    price_label: 'Jt/pax',
    cta_text: 'Detail Paket',
    is_active: true,
  },
  {
    product_sku: 'TOUR-SWISS-PARIS-7D-NOV26',
    category: 'wisata-populer',
    badge_label: 'Best Seller',
    title: '7D Scenic Switzerland & Paris',
    subtitle: 'Gunung Titlis & Keindahan Kota Eiffel',
    departure_date: '2026-11-20',
    airline: 'Singapore Airlines',
    hotel_makkah: '',
    hotel_madinah: '',
    duration_days: 7,
    feature_tags: 'Swiss Alps, Eiffel Sunset',
    normal_price: 41500000,
    publish_price: 38900000,
    price_label: 'Jt/pax',
    cta_text: 'Detail Paket',
    is_active: true,
  },
  {
    product_sku: 'TOUR-WEUROPE-9D-DES26',
    category: 'tour-reguler',
    badge_label: 'Group Tour',
    title: '9D Amazing West Europe',
    subtitle: 'Prancis, Belgia, Belanda & Jerman',
    departure_date: '2026-12-12',
    airline: 'Emirates',
    hotel_makkah: '',
    hotel_madinah: '',
    duration_days: 9,
    feature_tags: 'Eropa Barat, Amsterdam Cruise',
    normal_price: 34900000,
    publish_price: 32500000,
    price_label: 'Jt/pax',
    cta_text: 'Detail Paket',
    is_active: true,
  },
]

export const EMPTY_FORM = {
  product_sku: '',
  category: 'umroh',
  badge_label: '',
  title: '',
  subtitle: '',
  departure_date: '',
  airline: '',
  hotel_makkah: '',
  hotel_madinah: '',
  duration_days: '',
  feature_tags: '',
  normal_price: '',
  publish_price: '',
  price_label: 'Jt/pax',
  cta_text: 'Detail Paket',
  is_active: true,
}

export function categoryStyle(cat) {
  const map = {
    'umroh':          { bg: 'rgba(123,45,139,0.08)',  border: 'rgba(123,45,139,0.2)',  color: '#7B2D8B' },
    'umroh-mandiri':  { bg: 'rgba(123,45,139,0.06)',  border: 'rgba(123,45,139,0.15)', color: '#9B3AAE' },
    'muslim-tour':    { bg: 'rgba(245,166,35,0.08)',  border: 'rgba(245,166,35,0.2)',  color: '#B8760A' },
    'fit-products':   { bg: 'rgba(59,130,246,0.08)',  border: 'rgba(59,130,246,0.2)',  color: '#2563EB' },
    'wisata-populer': { bg: 'rgba(16,185,129,0.08)',  border: 'rgba(16,185,129,0.2)',  color: '#059669' },
    'tour-reguler':   { bg: 'rgba(107,114,128,0.08)', border: 'rgba(107,114,128,0.2)', color: '#6B7280' },
  }
  return map[cat] || map['tour-reguler']
}
